-- Handles the graphical part of the panel.
local Players = game:GetService("Players")
local UIS = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")

local GUI = script.Parent.Parent
local Theme = require(script.Parent.Theme)
local Shared = require(script.Parent.Shared)

local Panel = script.Parent.Parent
local SettingsContainer = Panel.Settings.ScrollingFrame
local DisplayFrame = Panel.MainFrame.ContentDisplay
local PlayerList = Panel.MainFrame.PlayerList

local CTRL_Down = false -- Used for multi selection
local PlayersSelected = {}
local PluginsName = Shared.GetPluginsName() -- {PluginName = {Name = Name}}
local SectionDisplayed = nil

--[[
-- ChangeSectionDisplayed(NewSection) accepts NewSection Frame argument and aims to facilitate the changing between
-- plugins functionality which was generated by the script.
--]]
local function ChangeSectionDisplayed(NewSection)
  if SectionDisplayed then SectionDisplayed.Visible = false end
  NewSection.Visible = true
  SectionDisplayed = NewSection
end

--[[
-- HandleBoolSetting(Name) accepts Name string as an argument and aims to centralize Bool related settings. Name **must** exist 
-- within SettingsContainer, else it will throw an error.
--]]
local function HandleBoolSetting(Name)
  if Panel:GetAttribute(Name) then
    SettingsContainer[Name].State.BackgroundColor3 = Color3.fromRGB(170, 0, 0)
  else
    SettingsContainer[Name].State.BackgroundColor3 = Color3.fromRGB(0, 170, 0)
  end

  Panel:SetAttribute(Name, not Panel:GetAttribute(Name))
end

--[[
-- RefreshPlayerList() can be called freely whenever the `PlayerList` ScrollingFrame has to be updated. Normally it's called
-- whenever a new player joins or a command is fired, after PlayersSelected table is cleared.
--]]
local function RefreshPlayerList()
  local Order = 0
  --[[
  -- CreatePlayerButton(Player) accepts a Player instance as argument and based on it and based on the provided settings it creates
  -- a new button or updates an existing button within PlayerList ScrollingFrame. Order variable has to be manually updated.
  --]]
  local function CreatePlayerButton(Player)
    local Template = PlayerList.Container:FindFirstChild(Player.Name)

    if not Template then
      -- If there isn't any existing button, simply create a new one with the template found within PlayerList and update its elements.
      Template = PlayerList.Container.Template:Clone()
      Template.ImageLabel.Image = game:GetService("Players"):GetUserThumbnailAsync(Player.UserId,
        Enum.ThumbnailType.HeadShot,
        Enum.ThumbnailSize.Size60x60)

      Player.Destroying:Connect(function()
        Template:Destroy()
      end)

      Template.Interact.MouseButton1Up:Connect(function()
        -- Holding down CTRL allows you to select multiple players at once. This aims to allow you do so.
        if CTRL_Down then
          if not table.find(PlayersSelected, Player) then
            table.insert(PlayersSelected, Player)
          else
            for i, v in pairs(PlayersSelected) do
              if v == Player then table.remove(PlayersSelected, i) end
            end
          end
        else
          PlayersSelected = {[1] = Player}
        end
      end)
    end

    Template.Parent = PlayerList
    Template.Name = Player.Name
    Template.LayoutOrder = Order -- Order is modified outside the function.

    Template.Visible = true
  end

  -- Considering that there may be players which aren't in a team, they should appear on top of other teams.
  for _, Player in pairs(Players:GetPlayers()) do
    Order = Order + 1
    CreatePlayerButton(Player)
  end

  -- In the end, update the PlayerList CanvasSize based on information given by the UIListLayout
  PlayerList.CanvasSize = UDim2.new(0, PlayerList.Container.UIListLayout.AbsoluteContentSize.X,
    0, PlayerList.Container.UIListLayout.AbsoluteContentSize.Y)
end

--[[
-- HandleVisibilityAnimation(Frame, In) accepts Frame instance and In bool arguments, and based on them play the popup / close
-- animation, whose properties are defined in Theme module. The function yields until animation is finished. In argument
-- is true when Scaling should go to 0 and false when scaling should go to 1.
--]]
local function HandleVisibilityAnimation(Frame, In)
  local Tween

  if In then
    Tween = TweenService:Create(Frame.UIScale, Theme.WindowClose, {Scale = 0})
  else
    Tween = TweenService:Create(Frame.UIScale, Theme.WindowPopup, {Scale = 1})
  end

  Tween:Play()
  if not In then Frame.Visible = true end
  Tween.Completed:Wait()
  if In then Frame.Visible = false end
end

Panel.PanelButton.MouseButton1Up:Connect(function()
  HandleVisibilityAnimation(Panel.MainFrame, Panel.MainFrame.Visible)
  -- if Panel.Terminal.Visible then HandleVisibilityAnimation(Panel.Terminal, true) end
end)

DisplayFrame.Parent.Commands.Container.Settings.MouseButton1Up:Connect(function()
  -- HandleVisibilityAnimation(Panel.Settings, Panel.Settings.Visible)
  ChangeSectionDisplayed(DisplayFrame.SettingsContainer)
end)

Players.PlayerAdded:Connect(function()
  RefreshPlayerList()
end)

UIS.InputBegan:Connect(function(Input, Processed)
  if Input.KeyCode == Enum.KeyCode.Equals and not Processed then
    HandleVisibilityAnimation(Panel.MainFrame, Panel.MainFrame.Visible)
    if Panel.Terminal.Visible then HandleVisibilityAnimation(Panel.Terminal, true) end
  elseif Input.KeyCode == Enum.KeyCode.LeftControl and not Processed then
    CTRL_Down = true
  end
end)

UIS.InputEnded:Connect(function(Input)
  if Input.KeyCode == Enum.KeyCode.LeftControl then
    CTRL_Down = false
  end
end)

-- This loop here wastes resources and the functionality should be reimplemented -@SuperPuiu
game:GetService("RunService").Stepped:Connect(function()
  for _, v in pairs(Panel.MainFrame.PlayerList.Container:GetChildren()) do
    if not v:IsA("Frame") or v.Name == "Template" then continue end

    if not table.find(PlayersSelected, Players:FindFirstChild(v.Name)) then
      v.BackgroundTransparency = 1
    else
      v.BackgroundTransparency = 0.8
    end
  end
end)

SettingsContainer.OutputOnExecution.State.MouseButton1Up:Connect(function()
  HandleBoolSetting("OutputOnExecution")
end)

SettingsContainer.TerminalVisibility.State.MouseButton1Up:Connect(function()
  HandleBoolSetting("TerminalVisibility")
  HandleVisibilityAnimation(Panel.Terminal, not Panel:GetAttribute("TerminalVisibility"))
end)

SettingsContainer.ResizingEnabled.State.MouseButton1Up:Connect(function()
  HandleBoolSetting("ResizingEnabled")
end)

SettingsContainer.PlayerButtonNaming.State.MouseButton1Up:Connect(function()
  SettingsContainer.PlayerButtonNaming.ScrollingFrame.Visible = true
end)

for Name, PluginTable in pairs(PluginsName) do
  if Name == "LocalCommands" then continue end
  if Panel.MainFrame.Commands:FindFirstChild(Name) then
    warn("[PANEL]: Category already exists. Continuing with other plugins.")
    continue
  end

  local Template = Panel.MainFrame.ContentDisplay.TemplateContainer:Clone()
  Template.Name = PluginTable.Name or Name
  -- Template.TextLabel.Text = PluginTable.Name or Name
  Template.Parent = Panel.MainFrame.ContentDisplay

  for P_Name, Plugin in pairs(PluginTable) do
    -- Ignore plugin metadata
    if P_Name == "Name" or P_Name == "Descriptions" or P_Name == "RequireExArguments" then continue end
    local ButtonTemplate = Template.Template:Clone()
    ButtonTemplate.Name = Plugin
    ButtonTemplate.TextLabel.Text = Plugin
    ButtonTemplate.Parent = Template
    ButtonTemplate.Visible = true
  end

  -- Template.CanvasSize = UDim2.new(0, Template.UIListLayout.AbsoluteContentSize.X,
  --  0, Template.UIListLayout.AbsoluteContentSize.Y)

  Template.Visible = true
end

for _, Button in pairs(GUI.MainFrame.Commands:GetDescendants()) do
  if not Button:IsA("TextButton") or Button.Name == "Settings" then continue end

  Button.MouseButton1Up:Connect(function()
    --[[Shared.RunCommand(Button.Name, PlayersSelected)
    PlayersSelected = {}
    RefreshPlayerList()]]
    ChangeSectionDisplayed(DisplayFrame[Button.Name])
  end)
end

if Panel:GetAttribute("AlwaysOnTop") then Shared.SetHighestDisplayOrder() end
Panel:SetAttribute("ResizingEnabled", true)
Panel:SetAttribute("OutputOnExecution", true)
RefreshPlayerList()
